eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

eureka.instance.prefer-ip-address=true

resilience4j.circuitbreaker.instances.restaurant.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.restaurant.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.restaurant.sliding-window-size=10
resilience4j.circuitbreaker.instances.restaurant.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.restaurant.permitted-number-of-calls-in-half-open-state=2

spring.cloud.openfeign.circuitbreaker.enabled=true

resilience4j.timelimiter.instances.foodCircuitBreaker.timeout-duration=10s

