eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

eureka.instance.prefer-ip-address=true

resilience4j.circuitbreaker.instances.restaurantService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.restaurantService.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.restaurantService.sliding-window-size=10
resilience4j.circuitbreaker.instances.restaurantService.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.restaurantService.permitted-number-of-calls-in-half-open-state=2

